version: "3.7"
services:
  redis:
    image: redis:alpine
    entrypoint: redis-server --appendonly yes
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis-data:/data

  mysql:
    image: mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin:5.0.4
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql

  backend:
    image: node:14.15.4
    command: >
      bash -c "
        [ ! -f ../scripts/wait ] && wget https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait -P ../scripts/ && chmod +x ../scripts/wait;
        ../scripts/wait && npm run dev
      "
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - node-modules:/usr/src/app/node_modules
      - wait-script:/usr/src/scripts
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: database
      DB_CONNECTION_LIMIT: 10
      REDIS_URL: redis
      NODE_ENV: development
      SESSION_SECRET: secret
      SESSION_STORE: redis
      PORT: 5000
      BCRYPT_SALT_ROUNDS: 10
      WAIT_HOSTS: mysql:3306
      WAIT_HOSTS_TIMEOUT: 60
    depends_on:
      - redis
      - mysql

volumes:
  mysql-data:
  redis-data:
  wait-script:
  node-modules:
